### ISSUE TITLE
there is no jump input ,and sometimes i can not move the caracter

### ISSUE THREAD

**Issue by stickylabdev** [TXDDTka/FreeBoom#27]

**Comment by TXDDTka** [comment]
It's very old version, we moved to new branch. Link to our's Discord with new version - https://discord.gg/2Wcdu5t.

**Comment by TXDDTka** [comment]
> _No description provided._

New version didn't help you anyway)

**Comment by stickylabdev** [comment]
All things are unclear, baby.

**Comment by stickylabdev** [comment]
I'm kicked out of the group... Ahaha.
